FROM java:8

EXPOSE 8083:8083

ADD /target/car-pooling-surcharge-calculator-service-0.0.1-SNAPSHOT.jar //

ENTRYPOINT ["java", "-jar", "/car-pooling-surcharge-calculator-service-0.0.1-SNAPSHOT.jar"]

